### ISSUE TITLE
Configuration issue: java.lang.NoClassDefFoundError: com.citrus.retrofit.CitrusEndPoint

### ISSUE THREAD

**Issue by tanmay-gp91** [citruspay/open-android-v3#79]
After spending hours upon this, I still can't get hold of this. Gradle builds without errors, tried complete clean and rebuild but still the runtime error is thrown everytime.
Using ANdroid Studio 1.4.1, Gradle 1.3.1

```
FATAL EXCEPTION: main
11-05 16:47:35.935 16682-16682/com.imli.main E/AndroidRuntime: Process: com.imli.main, PID: 16682
11-05 16:47:35.935 16682-16682/com.imli.main E/AndroidRuntime: java.lang.NoClassDefFoundError: com.citrus.retrofit.CitrusEndPoint
11-05 16:47:35.935 16682-16682/com.imli.main E/AndroidRuntime:     at com.citrus.retrofit.RetroFitClient.setupCitrusRetroFitClient(RetroFitClient.java:35)
11-05 16:47:35.935 16682-16682/com.imli.main E/AndroidRuntime:     at com.citrus.retrofit.RetroFitClient.initRetroFitClient(RetroFitClient.java:31)
11-05 16:47:35.935 16682-16682/com.imli.main E/AndroidRuntime:     at com.citrus.sdk.CitrusClient.initRetrofitClient(CitrusClient.java:292)
11-05 16:47:35.935 16682-16682/com.imli.main E/AndroidRuntime:     at com.citrus.sdk.CitrusClient.<init>(CitrusClient.java:141)
11-05 16:47:35.935 16682-16682/com.imli.main E/AndroidRuntime:     at com.citrus.sdk.CitrusClient.getInstance(CitrusClient.java:308)
11-05 16:47:35.935 16682-16682/com.imli.main E/AndroidRuntime:     at com.ample.main.activity.payment.PaymentActivity.onCreate(PaymentActivity.java:30)
```

**Comment by salilgodbole** [comment]
Hi,

Please have a look at this url. 
http://stackoverflow.com/a/31780564

Please enable multidex i think it should resolve your issues.

**Comment by yarolegovich** [comment]
Hi,
I'm running into the same issue and enabling multidex doesn't solve nothing (I don't understand how it supposed to solve it).

**Comment by salilgodbole** [comment]
Hi,

Can you please drop an email to mobiledev@citruspay.com
